FROM postgres:16-alpine

ENV postgres_user=postgres
ENV postgres_password=root
ENV postgres_db=auth_db


COPY requirements.txt .
COPY database.py .
COPY models.py .

RUN pip install -r requirements.txt

EXPOSE 5432